### ISSUE TITLE
Erro on load plugin nginx

### ISSUE THREAD

**Issue by welitonfreitas** [Staples-Inc/snap-plugin-collector-nginx#2]
Erro msg:
level=debug msg="2016/12/04 08:54:18 Error in getMetrics = invalid character 'A' looking for beginning of value" _module=plugin-exec io=stderr plugin=nginx

**Comment by IzabellaRaulin** [comment]
@welitonfreitas, could you provide your config file? Do you re-use an exemplary one which is available in [examples/conf](https://github.com/Staples-Inc/snap-plugin-collector-nginx/blob/master/examples/conf/) and run snapteld with this configuration, for example: 
`snapteld -t 0 -l 1 --config ./examples/conf/config.json`

**Comment by welitonfreitas** [comment]
This error occurs with the default nginx status module that does not return json. The plugin only works with the [Live Activity Monitoring of NGINX Plus](https://www.nginx.com/products/live-activity-monitoring/) paid module. More tested with the Opensource status module [nginx-module-vts](https://github.com/vozlt/nginx-module-vts) and it worked perfectly. Problem solved.
